/* Auto-generated by genmsg_cpp for file /home/xbar/groovy_workspace/Git/SpiderRobot_stack/SpiderRobot_pkg/msg/MYMSG.msg */
#ifndef SPIDERROBOT_PKG_MESSAGE_MYMSG_H
#define SPIDERROBOT_PKG_MESSAGE_MYMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace SpiderRobot_pkg
{
template <class ContainerAllocator>
struct MYMSG_ {
  typedef MYMSG_<ContainerAllocator> Type;

  MYMSG_()
  {
  }

  MYMSG_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MYMSG
typedef  ::SpiderRobot_pkg::MYMSG_<std::allocator<void> > MYMSG;

typedef boost::shared_ptr< ::SpiderRobot_pkg::MYMSG> MYMSGPtr;
typedef boost::shared_ptr< ::SpiderRobot_pkg::MYMSG const> MYMSGConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace SpiderRobot_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "SpiderRobot_pkg/MYMSG";
  }

  static const char* value(const  ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MYMSG_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::SpiderRobot_pkg::MYMSG_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // SPIDERROBOT_PKG_MESSAGE_MYMSG_H

